# Generated by Django 3.0.6 on 2020-05-29 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 29, 18, 9, 39, 645735)),
        ),
    ]
