# Generated by Django 3.0.6 on 2020-06-23 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200623_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='only_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='news_head',
            field=models.CharField(max_length=80),
        ),
    ]
