# Generated by Django 3.0.6 on 2020-06-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200625_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='id',
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='news_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
