# Generated by Django 3.0.6 on 2020-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200627_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='news_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
