# Generated by Django 3.0.6 on 2020-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200628_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='news_id',
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
